# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoxOneOpenSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'CryptoSwift'
    pod 'SwiftyRSA'
    pod 'Alamofire'
    pod 'SwiftyJSON'

  # Pods for opensdk

  target 'opensdkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SDKDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'CryptoSwift'
    pod 'SwiftyRSA'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    
end

